verbose: false              # Toggle verbosity level
laser_scan_topic: "/scan"   # Topic where the LiDAR scans are being placed
odom_topic: "/odo_laser"    # Topic where the odometry messages are being published
publish_tf: false           # Publish transform (base_link -> odom)
base_frame_id: "base_link"  # Robot base frame id
odom_frame_id: "odom"       # Odometry frame id
init_pose_from_topic: ""    # Topic from where the initial position of the robot should be taken
freq: 10.0                  # Publishing frequency (Hz)

# Covariance Matrices
pose_covariance_matrix: [7.8163e-05,          0,          0,          0,          0,          0,
                                  0, 7.8163e-05,          0,          0,          0,          0,
                                  0,          0, 7.8163e-05,          0,          0,          0,
                                  0,          0,          0, 7.8163e-05,          0,          0,
                                  0,          0,          0,          0, 7.8163e-05,          0,
                                  0,          0,          0,          0,          0, 7.8163e-05]
twist_covariance_matrix: [7.8163e-05,           0,       0,       0,       0,           0,
                                    0, 7.8163e-05,       0,       0,       0,           0,
                                    0,          0,  1.0e-9,       0,       0,           0,
                                    0,          0,       0,  1.0e-9,       0,           0,
                                    0,          0,       0,       0,  1.0e-9,           0,
                                    0,          0,       0,       0,       0,  1.1739e-05]

